@extends('frontend.layouts.app')

@section('content')

    <div class="homeslider owl-carousel owl-theme">
        <div class="item">
            <img src="{{asset('front/images/legal-banner.jpg')}}" alt="banner" />
            <div class="slide">
                <div class="col-md-6">
                    <div class="bcontent">
                        <div class="headings">Terms And  Conditions</div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <section class="lightbg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="listing">
                        <h5>PLEASE NOTE THAT YOUR USE OF AND ACCESS TO OUR SERVICES (DEFINED BELOW) ARE SUBJECT TO THE FOLLOWING TERMS; IF YOU DO NOT AGREE TO ALL OF THE FOLLOWING, YOU MAY NOT USE OR ACCESS THE SERVICES IN ANY MANNER.</h5>
                        <h5><b><center>Terms & Condition</center></b></h5>
                        <h5>Effective date: February 1, 2018</h5>
                        <h5>Welcome to www.gts.ai. Please read on to learn the rules and restrictions that govern your use of our website(s), products, services and applications (the “Services”). If you have any questions, comments, or concerns regarding these terms or the Services, please contact us at support@dash.gts.ai. These Terms of Use (the “Terms”) are a binding contract between you and GTS, Inc.. (“GTS,”“we” and “us”). You must agree to and accept all of the Terms, or you don’t have the right to use the Services. Your using the Services in any way means that you agree to all of these Terms, and these Terms will remain in effect while you use the Services. These Terms include the provisions in this document, as well as those in the Privacy Policy.</h5>
                        <h5><b>NOTICE:</b>Please read these Terms carefully. They cover important information about Services provided to you and any charges, taxes, and fees we bill you. These Terms include information about future changes to these Terms, automatic renewals , limitations of liability, a class action waiver, and resolution of disputes by arbitration instead of in court.</h5>
                        <h4 data-count="1">Will these Terms ever change?</h4>
                        <p>We are constantly trying to improve our Services, so these Terms may need to change along with the Services. We reserve the right to change the Terms at any time, but if we do, we will bring it to your attention by placing a notice on the www.gts.ai website, by sending you an email, and/or by some other means.
                            If you don’t agree with the new Terms, you are free to reject them; unfortunately, that means you will no longer be able to use the Services. If you use the Services in any way after a change to the Terms is effective, that means you agree to all of the changes.
                            Except for changes by us as described here, no other amendment or modification of these Terms will be effective unless in writing and signed by both you and us.</p>
                    </div>
                    <div class="listing">
                        <h4 data-count="2">What about my privacy?</h4>
                        <p>GTS takes the privacy of its users very seriously.
                            The Children’s Online Privacy Protection Act (“COPPA”) requires that online service providers obtain parental consent before they knowingly collect personally identifiable information online from children who are under 13. We do not knowingly collect or solicit personally identifiable information from children under 13; if you are a child under 13, please do not attempt to register for the Services or send any personal information about yourself to us. If we learn we have collected personal information from a child under 13, we will delete that information as quickly as possible. If you believe that a child under 13 may have provided us personal information, please contact us at support@dash.gts.ai.</p>
                    </div>
                    <div class="listing">
                        <h4 data-count="3">What are the basics of using www.gts.ai?</h4>
                        <p>You may be required to sign up for an account, and select a password and user name (“GTS User ID”). You promise to provide us with accurate, complete, and updated registration information about yourself. You may not select as your GTS User ID a name that you don’t have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission.
                            You represent and warrant that you are of legal age to form a binding contract (or if not, you’ve received your parent’s or guardian’s permission to use the Services and gotten your parent or guardian to agree to these Terms on your behalf). If you’re agreeing to these Terms on behalf of an organisation or entity, you represent and warrant that you are authorised to agree to these Terms on that organisation or entity’s behalf and bind them to these Terms (in which case, the references to “you” and “your” in these Terms, except for in this sentence, refer to that organisation or entity).
                            You will only use the Services for your own internal, personal, non-commercial use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you. If your use of the Services is prohibited by applicable laws, then you aren’t authorised to use the Services.
                            We can’t and won’t be responsible for your using the Services in a way that breaks the law.
                            You will not share your account or password with anyone, and you must protect the security of your account and your password. You’re responsible for any activity associated with your account.</p>
                    </div>
                    <div class="listing">
                        <h4 data-count="4">Your use of the Services is subject to the following additional restrictions:</h4>
                        <p>You represent, warrant, and agree that you will not contribute any Content or User Submission (each of those terms is defined below) or otherwise use the Services or interact with the Services in a manner that:

                            (a) Infringes or violates the intellectual property rights or any other rights of anyone else (including GTS);
                            (b) Violates any law or regulation, including, without limitation, any applicable export control laws;
                            (c) Is harmful, fraudulent, deceptive, threatening, harassing, defamatory, obscene, or otherwise objectionable;
                            (d) Jeopardises the security of your GTS account or anyone else’s (such as allowing someone else to log in to the Services as you);
                            (e) Attempts, in any manner, to obtain the password, account, or other security information from any other user;
                            (f) Violates the security of any computer network, or cracks any passwords or security encryption codes;
                            (g) Runs Mail-list, Listserv, any form of auto-responder or “spam” on the Services, or any processes that run or are activated while you are not logged into the Services, or that otherwise interfere with the proper working of the Services (including by placing an unreasonable load on the Services’ infrastructure);
                            (h) “Crawls,” “scrapes,” or “spiders” any page, data, or portion of or relating to the Services or Content (through use of manual or automated means);
                            (i) Copies or stores any significant portion of the Content;
                            (j) Decompiles, reverse engineers, or otherwise attempts to obtain the source code or underlying ideas or information of or relating to the Services.

                            A violation of any of the foregoing is grounds for termination of your right to use or access the Services.</p>
                        <div class="listing">
                            <h4 data-count="5">What are my rights in the Services?</h4>
                            <p>The materials displayed or performed or available on or through the Services, including, but not limited
                                to, text, graphics, data, articles, photos, images, illustrations, User Submissions, and so forth (all of the foregoing, the “Content”) are protected by copyright and/or other intellectual property laws. You promise to abide by all copyright notices, trademark rules, information, and restrictions contained in any Content you access through the Services, and you won’t use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell, commercialise or otherwise exploit for any purpose any Content not owned by you, (i) without the prior consent of the owner of that Content or (ii) in a way that violates someone else’s (including GTS’s) rights.
                                You understand that GTS owns the Services. You won’t modify, publish, transmit, participate in the transfer or sale of, reproduce (except as expressly provided in this Section), create derivative works based on, or otherwise exploit any of the Services.
                                The Services may allow you to copy or download certain Content; please remember that just because this functionality exists, doesn’t mean that all the restrictions above don’t apply – they do!</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="6">Do I have to grant any licenses to GTS or to other users?</h4>
                            <p>Anything you post, upload, share, store, or otherwise provide through the Services is your “User Submission.” Some User Submissions may be view-able by other users. In order to display your User Submissions on the Services, and to allow other users to enjoy them (where applicable), you grant us certain rights in those User Submissions. Please note that all of the following licenses are subject to our Privacy Policy to the extent they relate to User Submissions that are also your personally-identifiable information.
                                For all User Submissions, you hereby grant GTS a license to translate, modify (for technical purposes, for example making sure your content is view-able on an iPhone as well as a computer) and reproduce and otherwise act with respect to such User Submissions, in each case to enable us to operate the Services, as described in more detail below. This is a license only – your ownership in User Submissions is not affected.
                                If you store a User Submission in your own personal GTS account, in a manner that is not view-able by any other user except you (a “Personal User Submission”), you grant GTS the license above, as well as a license to display, perform, and distribute your Personal User Submission for the sole purpose of making that Personal User Submission accessible to you and providing the Services necessary to do so.
                                If you share a User Submission only in a manner that only certain specified users can view (for example, a private message to one or more other users)(a “Limited Audience User Submission”), then you grant GTS the licenses above, as well as a license to display, perform, and distribute your Limited Audience User Submission for the sole purpose of making that Limited Audience User Submission accessible to such other specified users, and providing the Services necessary to do so. Also, you grant such other specified users a license to access that Limited Audience User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.
                                If you share a User Submission publicly on the Services and/or in a manner that more than just you or certain specified users can view[, or if you provide us (in a direct email or otherwise) with any feedback, suggestions, improvements, enhancements, and/or feature requests relating to the Services] (each of the foregoing, a “Public User Submission”), then you grant GTS the licenses above, as well as a license to display, perform, and distribute your Public User Submission for the purpose of making that Public User Submission accessible to all GTS users and providing the Services necessary to do so, as well as all other rights necessary to use and exercise all rights in that Public User Submission in connection with the Services and/or otherwise in connection with GTS’s business for any purpose, provided that GTS will try to notify you if it uses your Public User Submission for any reason other than displaying it on the Services]. Also, you grant all other users of the Services a license to access that Public User Submission, and to use and exercise all rights in it, as permitted by the functionality of the Services.
                                You agree that the licenses you grant are royalty-free, perpetual, serviceable, irrevocable, and worldwide, provided that when you delete your GTS account, we will stop displaying your User Submissions (other than Public User Submissions, which may remain fully available)] to other users (if applicable), but you understand and agree that it may not be possible to completely delete that content from GTS’s records, and that your User Submissions may remain view-able elsewhere to the extent that they were copied or stored by other users.
                                Finally, you understand and agree that GTS, in performing the required technical steps to provide the Services to our users (including you), may need to make changes to your User Submissions to conform and adapt those User Submissions to the technical requirements of connection networks, devices, services, or media, and the foregoing licenses include the rights to do so.</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="7">What if I see something on the Services that infringes my copyright?</h4>
                            <p>You may have heard of the Digital Millennium Copyright Act (the “DMCA”), as it relates to online service providers, like GTS, being asked to remove material that allegedly violates someone’s copyright. We respect others’ intellectual property rights, and we reserve the right to delete or disable Content alleged to be infringing, and to terminate the accounts of repeat alleged infringers.</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="8">Who is responsible for what I see and do on the Services?</h4>
                            <p>Any information or content publicly posted or privately transmitted through the Services is the sole responsibility of the person from whom such content originated, and you access all such information and content at your own risk, and we aren’t liable for any errors or omissions in that information or content or for any damages or loss you might suffer in connection with it. We cannot control and have no duty to take any action regarding how you may interpret and use the Content or what actions you may take as a result of having been exposed to the Content, and you hereby release us from all liability for you having acquired or not acquired Content through the Services. We can’t guarantee the identity of any users with whom you interact in using the Services and are not responsible for which users gain access to the Services.
                                You are responsible for all Content you contribute, in any manner, to the Services, and you represent and warrant you have all rights necessary to do so, in the manner in which you contribute it. You will keep all your registration information accurate and current. You are responsible for all your activity in connection with the Services.
                                The Services may contain links or connections to third party websites or services that are not owned or controlled by GTS. When you access third party websites or use third party services, you accept that there are risks in doing so, and that GTS is not responsible for such risks. We encourage you to Your interactions with organisations and/or individuals found on or through the Services, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organisations and/or individuals. You should make whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties. You agree that GTS shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings.
                                If there is a dispute between participants on this site, or between users and any third party, you agree that GTS is under no obligation to become involved. In the event that you have a dispute with one or more other users, you release GTS, its officers, employees, agents, and successors from claims, demands, and damages of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes and/or our Services. If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: “general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.”</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="9">Will GTS ever change the Services?</h4>
                            <p>We’re always trying to improve the Services, so they may change over time. We may suspend or discontinue any part of the Services, or we may introduce new features or impose limits on certain features or restrict access to parts or all of the Services. We reserve the right to remove any Content from the Services at any time, for any reason (including, but not limited to, if someone alleges you contributed that Content in violation of these Terms), in our sole discretion, and without notice.</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="10">Do the Services cost anything?</h4>
                            <p>The Services are currently free, but we reserve the right to charge for certain or all Services in the future.
                                We will notify you before any Services you are then using begin carrying a fee, and if you wish to continue using such Services, you must pay all applicable fees for such Services.</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="11">What if I want to stop using the Services?</h4>
                            <p>You’re free to do that at any time, by contacting us at support@dash.gts.ai; please refer to our Privacy Policy, as well as the licenses above, to understand how we treat information you provide to us after you have stopped using our Services.
                                GTS is also free to terminate (or suspend access to) your use of the Services or your account, for any reason in our discretion, including your breach of these Terms. GTS has the sole right to decide
                                whether you are in violation of any of the restrictions set forth in these Terms.
                                Account termination may result in destruction of any Content associated with your account, so keep that in mind before you decide to terminate your account.
                                Provisions that, by their nature, should survive termination of these Terms shall survive termination. By way of example, all of the following will survive termination: any obligation you have to pay us or indemnify us, any limitations on our liability, any terms regarding ownership or intellectual property rights, and terms regarding disputes between us, including without limitation the arbitration agreement.</p>
                        </div>
                        <div class="listing">
                            <h4 data-count="12">What else do I need to know?</h4>
                            <p>Warranty Disclaimer. Neither GTS nor its licensors or suppliers make any representations or warranties concerning any content contained in or accessed through the Services, and we will not be responsible or liable for the accuracy, copyright compliance, legality, or decency of material contained in or accessed through the Services. We (and our licensors and suppliers) make no representations or warranties regarding suggestions or recommendations of services or products offered or purchased through the Services. Products and services purchased or offered (whether or not following such recommendations and suggestions) through the Services are provided “AS IS” and without any warranty of any kind from GTS or others (unless, with respect to such others only, provided expressly and unambiguously in writing by a designated third party for a specific product). THE SERVICES AND CONTENT ARE PROVIDED BY GTS (AND ITS LICENSORS AND SUPPLIERS) ON AN “AS-IS” BASIS, WITHOUT WARRANTIES OR ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.
                                Limitation of Liability.
                                TO THE FULLEST EXTENT ALLOWED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY (INCLUDING, WITHOUT LIMITATION, TORT, CONTRACT, STRICT LIABILITY, OR OTHERWISE) SHALL GTS(OR ITS LICENSORS OR SUPPLIERS) BE LIABLE TO YOU OR TO ANY OTHER PERSON FOR
                                (A) ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY KIND,INCLUDING DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, OR (B) ANY
                                AMOUNT, IN THE AGGREGATE, IN EXCESS OF THE GREATER OF (I) $100 OR (II) THE AMOUNTS PAID BY YOU TO GTS IN CONNECTION WITH THE SERVICES IN THE TWELVE (12) MONTH PERIOD PRECEDING THIS APPLICABLE CLAIM, OR (C) ANY MATTER
                                BEYOND OUR REASONABLE CONTROL. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO THE ABOVE LIMITATION AND EXCLUSIONS MAY NOT APPLY TO YOU.
                                Indemnity. To the fullest extent allowed by applicable law,] You agree to indemnify and hold GTS, its affiliates, officers, agents, employees, and partners harmless from and against any and all claims, liabilities, damages (actual and consequential), losses and expenses (including attorneys’ fees) arising from or in any way related to any third party claims relating to (a) your use of the Services (including any actions taken by a third party using your account), and (b) your violation of these Terms. In the event of such a claim, suit, or action (“Claim”), we will attempt to provide notice of the Claim to the contact information we have for your account (provided that failure to deliver such notice shall not eliminate or reduce your indemnification obligations here under).
                                Assignment. You may not assign, delegate or transfer these Terms or your rights or obligations here under, or your Services account, in any way (by operation of law or otherwise) without GTS’s prior written consent. We may transfer, assign, or delegate these Terms and our rights and obligations without consent.
                                Choice of Law. These Terms are governed by and will be construed under the Federal Arbitration Act, applicable federal law, and the laws of the State of Rajasthan, without regard to the conflicts of laws provisions thereof.
                                Arbitration Agreement. PLEASE READ THE FOLLOWING ARBITRATION AGREEMENT
                                CAREFULLY BECAUSE IT REQUIRES YOU TO ARBITRATE CERTAIN DISPUTES AND CLAIMS WITH GTS AND LIMITS THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM US.
                                Both you and GTS acknowledge and agree that for the purposes of any dispute arising out of or relating to the subject matter of these Terms, GTS’s officers, directors, employees and independent
                                contractors (“Personnel”) are third party beneficiaries of these Terms, and that upon your acceptance of these Terms, Personnel will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as the third party beneficiary hereof.
                                (a) Arbitration Rules; Applicability of Arbitration Agreement. Any dispute arising out of or relating to the subject matter of these Terms shall be finally settled by binding arbitration in India County, Rajasthan. The arbitration will proceed in the English language, in accordance with the Streamlined
                                Arbitration Rules and Procedures of Judicial Arbitration and Mediation Services, Inc. (“JAMS”) then in effect, by one commercial arbitrator with substantial experience in resolving intellectual property and commercial contract disputes, who shall be selected from the appropriate list of JAMS arbitrators in accordance with such Rules. Judgment upon the award rendered by such arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing obligation to arbitrate disputes, each party shall have the right to pursue injunctive or other equitable relief at any time, from any court of competent jurisdiction.
                                (b) Costs of Arbitration. The JAMS rules will govern payment of all arbitration fees. GTS will pay all arbitration fees for claims less than $75,000. GTS will not seek its attorneys’ fees and costs in
                                arbitration unless the arbitrator determines that your claim is frivolous.
                                (c) Small Claims Court. Furthermore, either you or GTS may assert claims, if they qualify, in small claims court in India, Rajasthan or any india States where you live or work.
                                (d) Waiver of Jury Trial. YOU AND GTS WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR JURY. You and GTS are instead choosing to have claims and disputes resolved by arbitration.
                                Arbitration procedures are typically more limited, more efficient, and less costly than rules applicable in court and are subject to very limited review by a court. In any litigation between you and GTS over
                                whether to vacate or enforce an arbitration award, YOU AND GTS WAIVE ALL RIGHTS TO A JURY TRIAL, and elect instead to have the dispute be resolved by a judge.
                                (e) Waiver of Class or Consolidated Actions. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED OR LITGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS. CLAIMS OF MORE THAN ONE
                                CUSTOMER OR USER CANNOT BE ARBITRATED OR LITGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER.
                                If however, this waiver of class or consolidated actions is deemed invalid or unenforceable, neither you nor we are entitled to arbitration; instead all claims and disputes will be resolved in a court as set forth in (g) below.
                                (f) Opt-out. You have the right to opt out of the provisions of this Section by sending written notice of your decision to opt out to the following address: TA-309, Captial Highstreet, Phool Bagh, Bhiwadi, Alwar (RJ.)- 301019 postmarked within 30 days of first accepting these Terms. You must include (1) your name and residence address; (2) the email address and/or telephone number associated with your account; and (3) a clear statement that you want to opt out of these Terms’ arbitration agreement.
                                (g) Exclusive Venue. If you send the opt-out notice in (f), and/or in any circumstances where the foregoing arbitration agreement permits either you or GTS to litigate any dispute arising out of or relating to the subject matter of these Terms in court, then the foregoing arbitration agreement will not apply to either party and both you and GTS agree that any judicial proceeding (other than small claims actions) will be brought in the state or federal courts located in, respectively, India County, Rajasthan, or the District of Rajasthan.
                                Miscellaneous. You will be responsible for paying, withholding, filing, and reporting all taxes, duties, and other governmental assessments associated with your activity in connection with the Services, provided that the GTS may, in its sole discretion, do any of the foregoing on your behalf or for itself as it sees fit. The failure of either you or us to exercise, in any way, any right herein shall not be deemed a waiver of any further rights here under. If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated, to the minimum extent necessary, so that these Terms shall otherwise remain in full force and effect and enforceable. You and GTS agree that these Terms are the complete and exclusive statement of the mutual understanding between you and GTS, and that these Terms supersede and cancel all previous written and oral agreements, communications and other understandings relating to the subject matter of these Terms,. You hereby acknowledge and agree that you are not an employee, agent, partner, or joint venture of GTS, and you do not have any authority of any kind to bind GTS in any respect whatsoever.
                                You and GTS agree there are no third party beneficiaries intended under these Terms.

                            </p>
                        </div>



                        <!----

                        <div class="heading3">
                            <h3>All Data Subject Requests can be made through our company website. Proof of identity is required.</h3>
                        </div>
                            <div class="listing">
                            <h4 data-count="18">General Disclaimers</h4>
                            <p>Neither we nor any of our affiliates, agents, contractors, employees or other representatives will be liable for losses arising out of or in connection with the use of our Sites to the extent permissible by law. We are only providing our Site and its contents on a “as is” basis and we make no (and expressly disclaim all) representations and/or warranties of any kind, express or implied, with respect to our Sites or its contents including without limitation warranties of merchantability and/or fitness for a particular purpose. In addition, we do not represent or warrant that the information accessible from or via our Sites is accurate, complete or current. The limitations of liability in relation to our Sites apply to all damages of any kind, including, without limitation, compensatory, direct, indirect or consequential damages, loss of data, loss of opportunity, income, production or profit, loss of or damage to property and claims of third parties. The limitations of liability in relation to our Sites do not limit our liability to the extent that it cannot be limited and/or excluded by applicable law. You are liable for any telephone charges and any charges made by your internet service provider as a result of your use of the internet service. Appen Limited, Level 6, 9 Help Street Chatswood NSW 2067 <a href="#">dpo@appen.com</a></p>
                        </div>
                    -->


                    </div>

                </div>
            </div>
    </section>

@endsection

